### ISSUE TITLE
Loading the entire DB into java heap

### ISSUE THREAD

**Issue by satur9nine** [polltery/Android-content-provider-example#1]
The adapter/loader implementation is basically wrong, you shouldn't load every single row of the database into a java arraylist. It works fine for 100 rows, it's really slow with 10,000 rows and likely just crashes with OOM with 10,000,000. The purpose of a cursor is that the adapter should have access to the cursor itself and load only what is needed to populate what is visible on screen.

**Comment by polltery** [comment]
@satur9nine thanks for pointing this out. I added a limit without pagination for now.
